### ISSUE TITLE
diffvg RuntimeError on render

### ISSUE THREAD

**Issue by mitchellgordon95** [dribnet/clipit_old#8]
Hey! I'm trying to run clipit on my own hardware (with an RTX A5000). I've got the environment set up more or less like the Colab notebook. I'm running this:

```
import sys
sys.path.append("clipit")
import clipit
clipit.reset_settings()
clipit.add_settings(prompts="Beirut skyline", aspect="widescreen")
clipit.add_settings(quality="better", scale=2.5)
clipit.add_settings(use_pixeldraw=True)
clipit.add_settings(num_cuts=10)
settings = clipit.apply_settings()
clipit.do_init(settings)
clipit.do_run(settings)
```

And getting a mysterious error from when calling `loss.backward()` in the train function:

```
(lightning) root@pytorch-6dc4c57d8d-l2h26:/app# python tmp.py
/root/miniconda3/envs/lightning/lib/python3.7/site-packages/comet_ml/monkey_patching.py:19: DeprecationWarning: the imp module is deprecated in favour of importlib; see the module's documentation for alternative uses
  import imp
/root/miniconda3/envs/lightning/lib/python3.7/site-packages/pkg_resources/__init__.py:1131: DeprecationWarning: Use of .. or absolute path in a resource path is not allowed and will raise exceptions in a future release.
  self, resource_name
/root/miniconda3/envs/lightning/lib/python3.7/site-packages/mlflow/types/schema.py:49: DeprecationWarning: `np.object` is a deprecated alias for the builtin `object`. To silence this warning, use `object` by itself. Doing this will not modify any behavior and is safe.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  binary = (7, np.dtype("bytes"), "BinaryType", np.object)
Using device: cuda:0
Optimising using: AdamP
Using text prompts: ['Beirut skyline']
Using seed: 6415327989839999698
0it [00:00, ?it/s]/root/miniconda3/envs/lightning/lib/python3.7/site-packages/torch/nn/functional.py:3613: UserWarning: Default upsampling behavior when mode=bilinear is changed to align_corners=False since 0.4.0. Please specify align_corners=True if the old behavior is desired. See the documentation of nn.Upsample for details.
  "See the documentation of nn.Upsample for details.".format(mode)
/root/miniconda3/envs/lightning/lib/python3.7/site-packages/kornia/utils/helpers.py:96: UserWarning: torch.solve is deprecated in favor of torch.linalg.solveand will be removed in a future PyTorch release.
torch.linalg.solve has its arguments reversed and does not return the LU factorization.
To get the LU factorization see torch.lu, which can be used with torch.lu_solve or torch.lu_unpack.
X = torch.solve(B, A).solution
should be replaced with
X = torch.linalg.solve(A, B) (Triggered internally at  /opt/conda/conda-bld/pytorch_1623448265233/work/aten/src/ATen/native/BatchLinearAlgebra.cpp:760.)
  out1, out2 = torch.solve(input.to(dtype), A.to(dtype))
iter: 0, loss: 2.97693, losses: 1.04082, 0.961298, 0.974818
0it [00:01, ?it/s]Oops: runtime error:
Try reducing --num-cuts to save memory
0it [00:01, ?it/s]
Traceback (most recent call last):
  File "tmp.py", line 11, in <module>
    clipit.do_run(settings)
  File "clipit/clipit.py", line 933, in do_run
    raise e
  File "clipit/clipit.py", line 925, in do_run
    train(args, cur_iteration)
  File "clipit/clipit.py", line 845, in train
    loss.backward()
  File "/root/miniconda3/envs/lightning/lib/python3.7/site-packages/torch/_tensor.py", line 255, in backward
    torch.autograd.backward(self, gradient, retain_graph, create_graph, inputs=inputs)
  File "/root/miniconda3/envs/lightning/lib/python3.7/site-packages/torch/autograd/__init__.py", line 149, in backward
    allow_unreachable=True, accumulate_grad=True)  # allow_unreachable flag
  File "/root/miniconda3/envs/lightning/lib/python3.7/site-packages/torch/autograd/function.py", line 87, in apply
    return self._forward_cls.backward(self, *args)  # type: ignore[attr-defined]
  File "/root/miniconda3/envs/lightning/lib/python3.7/site-packages/diffvg-0.0.1-py3.7-linux-x86_64.egg/pydiffvg/render_pytorch.py", line 709, in backward
    eval_positions.shape[0])
RuntimeError
```

I'm kind of at a loss, here (pun intended), since the RuntimeError doesn't have any message associated with it, and the function in question seems to be a compiled C function.  Any pointers would be appreciated.

**Comment by mitchellgordon95** [comment]
For reference, this is my Dockerfile:

```
FROM pytorchlightning/pytorch_lightning:base-conda-py3.7-torch1.9

ARG DEBIAN_FRONTEND=noninteractive

ENV APP_HOME /app
WORKDIR $APP_HOME

RUN apt-get install --yes git curl build-essential

COPY requirements.txt ./
RUN pip install --no-cache-dir -r ./requirements.txt

RUN git clone https://github.com/openai/CLIP
RUN git clone https://github.com/CompVis/taming-transformers.git
RUN git clone https://github.com/BachiLi/diffvg

# Compile diffvg
WORKDIR diffvg
RUN git submodule update --init --recursive
RUN conda install -y -c anaconda cmake
RUN conda install -y -c conda-forge ffmpeg
RUN export DIFFVG_CUDA=1; python setup.py install
WORKDIR ..

# I have no idea why we need this, given that we're using the
# pytorch-lightning base image.
RUN conda install -c conda-forge pytorch-lightning

# Clone clipit last, since it's the second most-likely to change
RUN git clone https://github.com/dribnet/clipit

# Copy local code to container image
COPY *.py ./
CMD ["python3", "model.py"]
```

and this is my requirements.txt:

```
ftfy
regex
tqdm
omegaconf
kornia
imageio-ffmpeg
einops
torch-optimizer
easydict
braceexpand
git+https://github.com/pvigier/perlin-numpy
svgwrite
svgpathtools
cssutils
numba
torch-tools
visdom
```

**Comment by dribnet** [comment]
Not sure, but one there is a bundled command line version of the app that might be worth trying:

```bash
python clipit.py \
  --use_pixeldraw True \
  --prompt 'Beirut skyline' \
  --output test1.png
```

**Comment by mitchellgordon95** [comment]
Well, I seemed to have fixed it. I added a few missing conda dependencies and installed torch manually using conda. Not sure what did it, but here's my Dockerfile for posterity.

```
# Note: we have two installations of CUDA. This one, which is
# system-wide, is needed for compiling diffvg from source. The other
# one (installed by conda below) is used by pytorch.
FROM nvidia/cuda:10.2-cudnn8-devel

ENV APP_HOME /app
WORKDIR $APP_HOME

RUN apt-get update
RUN apt-get install --yes git curl build-essential wget

RUN wget https://repo.anaconda.com/miniconda/Miniconda3-latest-Linux-x86_64.sh \
    && mkdir /root/.conda \
    && bash Miniconda3-latest-Linux-x86_64.sh -b

ENV PATH=$PATH:/root/miniconda3/bin

# Note: pytorch 1.9.0 + CUDA 11.1 does not work due to this bug:
# https://github.com/pytorch/pytorch/issues/52663
# We are using pytorch 1.9.0 + CUDA 10.2 because that's what works in colab.
RUN conda install cudatoolkit=10.2 -c nvidia
RUN conda install pytorch torchvision torchaudio -c pytorch -c nvidia
RUN conda install pytorch-lightning -c conda-forge

COPY requirements.txt ./
RUN pip install --no-cache-dir -r ./requirements.txt

RUN git clone https://github.com/openai/CLIP
RUN git clone https://github.com/CompVis/taming-transformers.git
RUN git clone https://github.com/BachiLi/diffvg

# Compile diffvg
WORKDIR diffvg
RUN git submodule update --init --recursive
RUN conda install -y numpy
RUN conda install -y scikit-image
RUN conda install -y -c anaconda cmake
RUN conda install -y -c conda-forge ffmpeg
RUN export DIFFVG_CUDA=1; python setup.py install
WORKDIR ..


# Clone clipit last, since it's the second most-likely to change
RUN git clone https://github.com/dribnet/clipit

# Copy local code to container image
COPY *.py ./
CMD ["python3", "model.py"]
```
